begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select has_column('public','linked_contacts','is_primary_payer','Primary payer responsibility is additive');
select has_column('public','linked_contacts','is_primary_scheduling_contact','Scheduling responsibility is additive');
select has_column('public','linked_contacts','receives_financial_escalations','Escalation responsibility is additive');
select ok((select relrowsecurity from pg_class where oid='public.automation_rules'::regclass),'Rules have RLS');
select ok((select relrowsecurity from pg_class where oid='public.automation_runs'::regclass),'Runs have RLS');
select ok(not has_table_privilege('anon','public.automation_rules','SELECT'),'Anonymous users cannot read rules');
select ok(not has_table_privilege('anon','public.automation_runs','SELECT'),'Anonymous users cannot read automation history');
select ok(not has_table_privilege('authenticated','public.automation_rules','UPDATE'),'Rule writes require the validated coach API');
select ok(not has_table_privilege('authenticated','public.automation_runs','INSERT'),'Portal users cannot forge run history');
select ok(has_table_privilege('service_role','public.automation_rules','INSERT'),'Privileged worker can manage rules');
select ok(has_table_privilege('service_role','public.automation_runs','INSERT'),'Privileged worker can record decisions');
select ok(not has_function_privilege('anon','public.suppress_obsolete_lesson_automation()','EXECUTE'),'Anonymous users cannot invoke the suppression trigger function');
select ok(not has_function_privilege('authenticated','public.suppress_resolved_booking_automation()','EXECUTE'),'Booking suppression is not a client RPC');
select ok((select indisunique and indpred is not null from pg_index where indexrelid='public.linked_contacts_one_primary_payer'::regclass),'Primary payer uniqueness is partial');
select ok((select indisunique and indpred is not null from pg_index where indexrelid='public.linked_contacts_one_primary_scheduler'::regclass),'Primary scheduler uniqueness is partial');
select has_column('public','outbox_messages','suppression_reason','Canceled queue history keeps the reason');
set local role authenticated;
select set_config('request.jwt.claim.sub','10000000-0000-0000-0000-000000000099',true);
select is((select count(*) from public.automation_rules),0::bigint,'Unrelated portal identity sees no rules');
select is((select count(*) from public.automation_runs),0::bigint,'Unrelated portal identity sees no decisions');
select * from finish();
rollback;
