import { BookOpen, CalendarDays, CheckSquare, CircleDollarSign, FileText, FolderOpen, Home, LogOut, Menu, UserRound } from "lucide-react";
import { NavLink, Navigate, Route, Routes, useNavigate } from "react-router-dom";
import { useStudio } from "../../hooks/useStudio";
import { formatMoney, packageSummary, studentBalanceMinor } from "../../domain/finance";
import { EmptyState, Section, Status } from "../../components/Primitives";
import type { Assignment, Lesson, Material, StudioSnapshot } from "../../domain/model";
import type { LucideIcon } from "lucide-react";

const tabs = [["", "Home", Home], ["work", "Current Work", BookOpen], ["lessons", "Lessons", CalendarDays], ["practice", "Practice", CheckSquare], ["materials", "Materials", FolderOpen], ["payments", "Payments", CircleDollarSign], ["actor-page", "Actor Page", UserRound]] as const;
export function StudentPortal() {
  const { data, isLoading } = useStudio("student", "student-maya");
  if (isLoading || !data) return <div className="loading">Preparing your workspace…</div>;
  return <div className="student-shell"><aside><div className="wordmark">Stage <b>&amp;</b> Story</div><nav>{tabs.map(([to,label,Icon])=><NavLink key={to} to={`/portal/${to}`} end={!to}><Icon/><span>{label}</span></NavLink>)}</nav><div className="identity"><span>MK</span><div><strong>Maya Kim</strong><small>Student</small></div></div></aside><main><Routes><Route index element={<StudentHome data={data}/>} /><Route path="work" element={<Work data={data}/>} /><Route path="lessons" element={<Lessons data={data}/>} /><Route path="practice" element={<Practice data={data}/>} /><Route path="materials" element={<Materials data={data}/>} /><Route path="payments" element={<Payments data={data}/>} /><Route path="actor-page" element={<ActorPage data={data}/>} /><Route path="*" element={<Navigate to="/portal" replace/>}/></Routes></main><nav className="mobile-nav student-mobile">{tabs.slice(0,4).map(([to,label,Icon])=><NavLink key={to} to={`/portal/${to}`} end={!to}><Icon/><span>{label}</span></NavLink>)}<NavLink to="/portal/materials"><Menu/><span>More</span></NavLink></nav></div>;
}
type Snapshot = StudioSnapshot;
function Header({data}:{data:Snapshot}) { return <header className="student-header"><h1>Welcome back, {data.displayName}</h1><p>You’ve got a great plan. Let’s keep the momentum.</p></header>; }
function PortalRow({icon:Icon,title,detail,action}:{icon:LucideIcon;title:string;detail:string;action:string}) { return <div className="portal-row"><Icon/><div><strong>{title}</strong><small>{detail}</small></div><button>{action}<span>›</span></button></div>; }
function StudentHome({data}:{data:Snapshot}) { const lesson=data.lessons.find((item)=>item.status==="scheduled"); const work=data.materials.find((item)=>item.role==="current_script"); const practice=data.assignments.find((item)=>item.status!=="completed"); const material=data.materials.find((item)=>item.role!=="current_script"); const pkg=data.packages[0]; return <div className="student-page"><Header data={data}/><Section title="Continue your work" marked>{work?<PortalRow icon={FileText} title={work.title} detail="Pick up where you left off." action="Open script"/>:<EmptyState title="No current work yet" detail="Your coach will place your active script here."/>}</Section><Section title="Next lesson">{lesson?<PortalRow icon={CalendarDays} title={lesson.topic} detail={`${new Date(lesson.startsAt).toLocaleString()} · ${lesson.locationLabel}`} action="View lesson"/>:<EmptyState title="No lesson scheduled" detail="Your coach owns the calendar and will share the next confirmed time."/>}</Section><Section title="Your practice" marked>{practice?<PortalRow icon={CheckSquare} title={practice.title} detail={practice.details} action="Open"/>:<EmptyState title="Practice is complete" detail="New assignments will appear after your coach publishes them."/>}</Section><Section title="Your materials" marked>{material?<PortalRow icon={FolderOpen} title={material.title} detail={material.category} action="View"/>:<EmptyState title="No shared materials" detail="Nothing is missing on your side; your coach has not shared one yet."/>}</Section>{pkg&&<Section title="Your package" marked><PortalRow icon={CircleDollarSign} title={pkg.name} detail={`${packageSummary(pkg,data.creditEntries).remainingCredits} sessions remaining`} action={formatMoney(Math.max(0,studentBalanceMinor(data.students[0].id,data.payments)))}/></Section>}</div>; }
function Work({data}:{data:Snapshot}) { const work=data.materials.filter((item)=>item.role==="current_script"); return <PortalList title="Current Work" description="The one active script and its connected practice." items={work.map((item)=>({title:item.title,detail:item.category,status:item.status}))}/>; }
function Lessons({data}:{data:Snapshot}) { return <PortalList title="Lessons" description="Confirmed upcoming lessons and completed history." items={data.lessons.map((item)=>({title:item.topic,detail:new Date(item.startsAt).toLocaleString(),status:item.status}))}/>; }
function Practice({data}:{data:Snapshot}) { return <PortalList title="Practice" description="Published assignments you can complete, reopen, or ask about." items={data.assignments.map((item)=>({title:item.title,detail:item.details,status:item.status}))}/>; }
function Materials({data}:{data:Snapshot}) { return <PortalList title="Materials" description="Only active materials your coach has intentionally shared." items={data.materials.map((item)=>({title:item.title,detail:item.category,status:item.status}))}/>; }
function Payments({data}:{data:Snapshot}) { const pkg=data.packages[0]; return <PortalList title="Payments" description="Package credits and confirmed payment history from the ledger." items={pkg?[{title:pkg.name,detail:`${packageSummary(pkg,data.creditEntries).remainingCredits} sessions remaining`,status:"active"}]:[]}/>; }
function ActorPage({data}:{data:Snapshot}) { return <PortalList title="Actor Page" description="Edit a draft and submit it for coach review before publishing." items={data.actorProfiles.map((profile)=>({title:profile.displayName,detail:`/actors/${profile.slug}`,status:profile.status}))}/>; }
function PortalList({title,description,items}:{title:string;description:string;items:{title:string;detail:string;status:string}[]}) { return <div className="student-page"><header className="student-header"><h1>{title}</h1><p>{description}</p></header><Section title={title} marked><div className="table-list">{items.map((item,index)=><article key={`${item.title}-${index}`}><FileText/><div><strong>{item.title}</strong><small>{item.detail}</small></div><Status tone={item.status.includes("complete")||item.status==="active"?"good":"neutral"}>{item.status.replaceAll("_"," ")}</Status><button>Open</button></article>)}{!items.length&&<EmptyState title={`No ${title.toLowerCase()} yet`} detail="Nothing is required from you right now."/>}</div></Section></div>; }
