import { CircleDollarSign, Gift, ShieldCheck } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { formatMoney } from "../../domain/finance";

type Catalog={package:{id:string;name:string;description:string;sessionCount:number;sessionDurationMinutes:number;priceMinor:number;currency:string;deliveryFormat?:string};studio?:{name?:string;settings?:Record<string,unknown>}};
export default function PackageGift(){
  const {definitionId,token}=useParams();
  const [catalog,setCatalog]=useState<Catalog>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [claimed,setClaimed]=useState(false);
  useEffect(()=>{if(!definitionId)return;fetch(`/api/v2/public/package-gifts/catalog?definitionId=${encodeURIComponent(definitionId)}`).then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.message||"Gift package unavailable.");setCatalog(body);}).catch((reason)=>setError(reason instanceof Error?reason.message:"Gift package unavailable."));},[definitionId]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(busy)return;setBusy(true);setError("");try{const values=Object.fromEntries(new FormData(event.currentTarget));const action=token?"claim":"create";const response=await fetch(`/api/v2/public/package-gifts/${action}`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(token?{...values,token,createPortalProfile:values.createPortalProfile==="on",autoApply:values.autoApply==="on"}:{...values,definitionId})});const body=await response.json();if(!response.ok)throw new Error(body.message||"The gift could not be processed.");if(body.url)window.location.assign(body.url);else setClaimed(true);}catch(reason){setError(reason instanceof Error?reason.message:"The gift could not be processed.");setBusy(false);}};
  if(claimed)return <main className="gift-page"><section className="gift-card gift-success"><ShieldCheck/><h1>Your gift is ready</h1><p>The lesson credits are in your account. If you requested a portal, login instructions are sending now.</p><Link className="button-link primary" to="/login">Open Coach’D</Link></section></main>;
  if(token)return <main className="gift-page"><section className="gift-card"><Gift/><small>Coach’D package gift</small><h1>Claim your lesson package</h1><p>Use the same email address that received this private gift link.</p>{error&&<p className="inline-error" role="alert">{error}</p>}<form className="workflow-form" onSubmit={submit}><label>Full name<input name="fullName" required/></label><label>Email<input name="email" type="email" required/></label><label className="check-row full"><input name="autoApply" type="checkbox"/>Apply credits to eligible upcoming unpaid lessons</label><label className="check-row full"><input name="createPortalProfile" type="checkbox" defaultChecked/>Create a portal profile and email login instructions</label><button className="primary full" disabled={busy}>{busy?"Claiming…":"Claim gift"}</button></form></section></main>;
  if(!catalog&&!error)return <div className="loading">Opening gift package…</div>;
  return <main className="gift-page"><section className="gift-card"><Gift/><small>{catalog?.studio?.name||"Coach’D"}</small><h1>Give coaching that keeps moving forward</h1>{catalog&&<div className="gift-package-summary"><CircleDollarSign/><div><strong>{catalog.package.name}</strong><span>{catalog.package.sessionCount} lessons · {catalog.package.sessionDurationMinutes} minutes each</span></div><b>{formatMoney(catalog.package.priceMinor,catalog.package.currency)}</b></div>}{error&&<p className="inline-error" role="alert">{error}</p>}{catalog&&<form className="workflow-form" onSubmit={submit}><label>Your name<input name="purchaserName" required/></label><label>Your email<input name="purchaserEmail" type="email" required/></label><label>Recipient name<input name="recipientName" required/></label><label>Recipient email<input name="recipientEmail" type="email" required/></label><label>Delivery date<input name="deliveryDate" type="date" min={new Date().toISOString().slice(0,10)}/><small>Leave blank to send after payment.</small></label><label className="full">Optional message<textarea name="message" maxLength={500}/></label><p className="portal-notice full">This is a one-time gift. It never starts a subscription or recurring charge.</p><button className="primary full" disabled={busy}>{busy?"Opening secure checkout…":"Continue to Stripe"}</button></form>}<Link to="/book">Back to booking</Link></section></main>;
}
