import type { Config } from "@netlify/functions";
import { googleAccessToken } from "./_shared/google";
import { serviceClient } from "./_shared/supabase";

export default async()=>{
  const db=serviceClient(),{data:items,error}=await db.rpc("claim_calendar_projections",{batch_size:10});if(error)throw error;if(!items?.length)return Response.json({ok:true,processed:0});
  const token=await googleAccessToken(),calendar=encodeURIComponent(Netlify.env.get("GOOGLE_CALENDAR_ID")||"primary"),studioNames=new Map<string,string>();let projected=0;
  for(const item of items){const p=item.projection,l=item.lesson;try{
    if(["cancelled","late_cancelled"].includes(l.status)){if(p.external_event_id){const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${calendar}/events/${encodeURIComponent(p.external_event_id)}?sendUpdates=all`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(!response.ok&&![404,410].includes(response.status))throw new Error(await response.text());}await db.from("calendar_projections").update({status:"projected",projected_version:l.version,last_projected_at:new Date().toISOString(),last_error:null,attempts:0,next_attempt_at:null}).eq("id",p.id);projected++;continue;}
    const [{data:participants},{data:studio}]=await Promise.all([db.from("lesson_participants").select("email").eq("lesson_id",l.id).eq("status","confirmed"),studioNames.has(l.studio_id)?Promise.resolve({data:null}):db.from("studios").select("name").eq("id",l.studio_id).single()]);if(studio?.name)studioNames.set(l.studio_id,studio.name);const studioName=studioNames.get(l.studio_id)||"Studio";
    const body:any={summary:l.topic,start:{dateTime:l.starts_at},end:{dateTime:l.ends_at},location:l.location_label,description:[`Managed by ${studioName}`,l.join_url&&l.meeting_provider!=="google_meet"?`Join: ${l.join_url}`:null].filter(Boolean).join("\n"),attendees:(participants||[]).filter((participant)=>participant.email).map((participant)=>({email:participant.email}))};
    if(l.meeting_provider==="google_meet"&&!p.external_event_id)body.conferenceData={createRequest:{requestId:p.conference_request_id||`meet-${l.id}`,conferenceSolutionKey:{type:"hangoutsMeet"}}};
    const base=p.external_event_id?`https://www.googleapis.com/calendar/v3/calendars/${calendar}/events/${encodeURIComponent(p.external_event_id)}`:`https://www.googleapis.com/calendar/v3/calendars/${calendar}/events`,url=`${base}?conferenceDataVersion=1&sendUpdates=all`,response=await fetch(url,{method:p.external_event_id?"PATCH":"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json() as {id?:string;etag?:string;hangoutLink?:string;conferenceData?:{entryPoints?:{entryPointType:string;uri:string}[]}};if(!response.ok)throw new Error(JSON.stringify(result));
    const joinUrl=result.hangoutLink||result.conferenceData?.entryPoints?.find((entry)=>entry.entryPointType==="video")?.uri;await Promise.all([db.from("calendar_projections").update({external_event_id:result.id||p.external_event_id,external_version:result.etag,projected_version:l.version,status:"projected",last_projected_at:new Date().toISOString(),last_error:null,attempts:0,next_attempt_at:null}).eq("id",p.id),joinUrl?db.from("lessons").update({join_url:joinUrl,location_label:"Google Meet",updated_at:new Date().toISOString()}).eq("id",l.id):Promise.resolve()]);projected++;
  }catch(error){const delayMinutes=Math.min(60,Math.max(1,2**Math.min(Number(p.attempts||1),6)));await db.from("calendar_projections").update({status:"failed",last_error:String(error),next_attempt_at:new Date(Date.now()+delayMinutes*60_000).toISOString()}).eq("id",p.id);}}
  return Response.json({ok:true,processed:items.length,projected});
};
export const config:Config={schedule:"*/5 * * * *"};
