import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { render,screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { describe,expect,it } from "vitest";
import { App } from "./App";
const renderApp=(path="/")=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[path]}><App/></MemoryRouter></QueryClientProvider>);
describe("studio surfaces",()=>{
  it("shows one explainable coach next action",async()=>{renderApp();expect(await screen.findByRole("heading",{name:/good morning/i})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Up next"})).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:/open/i}));expect(screen.getByRole("heading",{name:/review liam foster/i})).toBeInTheDocument();expect(screen.getByText("Why this is here")).toBeInTheDocument()});
  it("prioritizes student work and next lesson",async()=>{renderApp("/portal");expect(await screen.findByRole("heading",{name:/welcome back/i})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Continue your work"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Next lesson"})).toBeInTheDocument()});
  it("does not publish draft actor profiles",async()=>{renderApp("/actors/maya-kim");expect(await screen.findByRole("heading",{name:"Actor page unavailable"})).toBeInTheDocument()});
  it("shows the public service catalog and complete booking funnel",async()=>{const catalog=renderApp("/book");expect(await screen.findByRole("heading",{name:/find the right room/i})).toBeInTheDocument();expect(screen.getAllByRole("link",{name:/view times/i}).length).toBeGreaterThan(0);catalog.unmount();renderApp("/book/private-acting-coaching");expect(await screen.findByRole("heading",{name:/how would you like to meet/i})).toBeInTheDocument();expect(screen.getByRole("button",{name:/google meet/i})).toBeInTheDocument()});
  it("shows every coach booking management view",async()=>{renderApp("/bookings");expect(await screen.findByRole("heading",{name:"Bookings"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Services"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Availability"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Classes & courses"})).toBeInTheDocument();});
  it("shows student booking and recurring self-service",async()=>{renderApp("/portal/bookings");expect(await screen.findByRole("heading",{name:"Bookings"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Recurring plans"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Reschedule"})).toBeInTheDocument();});
  it("scopes the guest management view to one booking",async()=>{renderApp("/booking/demo-maya");expect(await screen.findByRole("heading",{name:"Private Acting Coaching"})).toBeInTheDocument();expect(screen.getByText(/SS-1048/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"Cancel booking"})).toBeInTheDocument();});
  it("offers password login and the current terms",async()=>{renderApp("/login");expect(await screen.findByLabelText("Username")).toBeInTheDocument();expect(screen.getByLabelText("Password")).toBeInTheDocument();expect(screen.getByRole("link",{name:"Terms and Conditions"})).toHaveAttribute("href","/terms");});
  it("renders the supplied terms document",async()=>{renderApp("/terms");expect(await screen.findByRole("heading",{name:"Coach Darius Terms and Conditions"})).toBeInTheDocument();expect(screen.getByText(/Effective Date: August 20, 2026/)).toBeInTheDocument();});
});
