import { Eraser, Highlighter, MousePointer2, Pencil, Plus, Redo2, Save, Table2, TextCursorInput, Undo2, Upload, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { useQueryClient } from "@tanstack/react-query";
import type { Lesson, LessonWhiteboard as WhiteboardRecord, Material, Student, StudioSnapshot, WhiteboardElement } from "../domain/model";
import { studioCommand } from "../data/bookingCommands";
import { uploadStudioFile } from "../data/uploads";

type Tool = "select" | "draw" | "highlight" | "erase" | "text" | "table";
type Props = { data: StudioSnapshot; lesson: Lesson; student: Student; isDemo: boolean; onDemoChange?: (board: WhiteboardRecord) => void };
const freshDocument = () => ({ version: 1, elements: [] as WhiteboardElement[] });

export function LessonWhiteboard(props: Props) {
  const [open, setOpen] = useState(false);
  const exists = props.data.lessonWhiteboards.some((item) => item.lessonId === props.lesson.id);
  return <>
    <section className="whiteboard-launcher"><div><strong>{exists ? "Shared lesson whiteboard" : "Add a whiteboard when this lesson needs one"}</strong><p>{exists ? "Open the saved board for drawing, text, PDFs, highlights, and tables." : "No whiteboard exists for this lesson yet."}</p></div><button type="button" className={exists ? "button-link" : "primary-button"} onClick={() => setOpen(true)}>{exists ? <MousePointer2 /> : <Plus />}{exists ? "Open whiteboard" : "Add whiteboard"}</button></section>
    {open && <div className="whiteboard-modal" role="dialog" aria-modal="true" aria-label="Lesson whiteboard"><button className="whiteboard-modal-backdrop" aria-label="Close whiteboard" onClick={() => setOpen(false)} /><div className="whiteboard-modal-panel"><WhiteboardCanvas {...props} onClose={() => setOpen(false)} /></div></div>}
  </>;
}

function WhiteboardCanvas({ data, lesson, student, isDemo, onDemoChange, onClose }: Props & { onClose: () => void }) {
  const existing = data.lessonWhiteboards.find((item) => item.lessonId === lesson.id);
  const initial = useMemo(() => structuredClone(existing?.document || freshDocument()), [existing?.id]);
  const [document, setDocument] = useState(initial), [history, setHistory] = useState<typeof document[]>([]), [future, setFuture] = useState<typeof document[]>([]);
  const [tool, setTool] = useState<Tool>("select"), [color, setColor] = useState("#173f35"), [width, setWidth] = useState(3), [fontSize, setFontSize] = useState(20), [fontFamily, setFontFamily] = useState("Inter"), [underline, setUnderline] = useState(false);
  const [notice, setNotice] = useState(""), [saving, setSaving] = useState(false), [dirty, setDirty] = useState(!existing), [assetUrls, setAssetUrls] = useState<Record<string, string>>({});
  const [insert,setInsert]=useState<{type:"text"|"table";x:number;y:number}>(), [insertValue,setInsertValue]=useState("");
  const board = useRef<HTMLDivElement>(null), drawing = useRef<string | undefined>(undefined), dragging = useRef<{ id: string; dx: number; dy: number } | undefined>(undefined), queryClient = useQueryClient();
  useEffect(() => { const keyboard = (event: KeyboardEvent) => { if (event.key !== "Escape") return; if (tool !== "select") setTool("select"); else onClose(); }; window.addEventListener("keydown", keyboard); return () => window.removeEventListener("keydown", keyboard); }, [tool, onClose]);
  const commit = (next: typeof document) => { setHistory((items) => [...items.slice(-49), structuredClone(document)]); setFuture([]); setDocument(next); setDirty(true); };
  const point = (event: ReactPointerEvent) => { const rect = board.current!.getBoundingClientRect(); return { x: Math.max(0, Math.min(1200, (event.clientX - rect.left) * 1200 / rect.width)), y: Math.max(0, Math.min(720, (event.clientY - rect.top) * 720 / rect.height)) }; };
  const pointerDown = (event: ReactPointerEvent) => {
    event.preventDefault(); const value = point(event);
    if (tool === "draw" || tool === "highlight") { const id = crypto.randomUUID(); drawing.current = id; commit({ ...document, elements: [...document.elements, { id, type: "path", points: [value], color: tool === "highlight" ? "#f4d35e" : color, width: tool === "highlight" ? Math.max(14, width * 4) : width, highlighted: tool === "highlight" }] }); event.currentTarget.setPointerCapture(event.pointerId); }
    else if (tool === "erase") { const target = [...document.elements].reverse().find((item) => item.type === "path" ? item.points.some((entry) => Math.hypot(entry.x - value.x, entry.y - value.y) <= Math.max(18, item.width * 1.5)) : value.x >= item.x && value.x <= item.x + item.width && value.y >= item.y && value.y <= item.y + item.height); if (target) commit({ ...document, elements: document.elements.filter((entry) => entry.id !== target.id) }); }
    else if (tool === "text") { setInsert({type:"text",...value});setInsertValue("");setTool("select"); }
    else if (tool === "table") { setInsert({type:"table",...value});setInsertValue("3x3");setTool("select"); }
  };
  const pointerMove = (event: ReactPointerEvent) => { const value = point(event); if (drawing.current) setDocument((current) => ({ ...current, elements: current.elements.map((item) => item.id === drawing.current && item.type === "path" ? { ...item, points: [...item.points, value] } : item) })); if (dragging.current) { const { id, dx, dy } = dragging.current; setDocument((current) => ({ ...current, elements: current.elements.map((item) => item.id === id && item.type !== "path" ? { ...item, x: value.x - dx, y: value.y - dy } : item) })); setDirty(true); } };
  const pointerUp = () => { drawing.current = undefined; dragging.current = undefined; };
  const objectPointer = (event: ReactPointerEvent, item: Exclude<WhiteboardElement, { type: "path" }>) => { event.stopPropagation(); if (tool === "erase") { commit({ ...document, elements: document.elements.filter((entry) => entry.id !== item.id) }); return; } if (tool !== "select") return; const value = point(event); dragging.current = { id: item.id, dx: value.x - item.x, dy: value.y - item.y }; event.currentTarget.setPointerCapture(event.pointerId); };
  const undo = () => { const previous = history.at(-1); if (!previous) return; setFuture((items) => [structuredClone(document), ...items]); setDocument(previous); setHistory((items) => items.slice(0, -1)); setDirty(true); }, redo = () => { const next = future[0]; if (!next) return; setHistory((items) => [...items, structuredClone(document)]); setDocument(next); setFuture((items) => items.slice(1)); setDirty(true); };
  const save = async () => { if (saving) return; setSaving(true); try { if (isDemo) onDemoChange?.({ id: existing?.id || `whiteboard-${crypto.randomUUID()}`, studioId: data.studioId, lessonId: lesson.id, document, version: (existing?.version || 0) + 1, updatedAt: new Date().toISOString() }); else { await studioCommand("whiteboards", { command: "save", entityId: lesson.id, expectedVersion: existing?.version || 0, payload: { document }, reason: "Lesson whiteboard saved" }); await queryClient.invalidateQueries({ queryKey: ["studio"] }); } setDirty(false); setNotice("Whiteboard saved for both coach and student."); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Whiteboard could not be saved."); } finally { setSaving(false); } };
  const addPdf = async (file?: File) => { if (!file) return; if (file.type !== "application/pdf") { setNotice("Choose a PDF to place on the board."); return; } setSaving(true); try { if (isDemo) { setNotice("PDF placement uses secure file storage in the live studio."); return; } const stored = await uploadStudioFile({ studioId: data.studioId, studentId: student.id, entityType: "lesson", entityId: lesson.id, file, visibility: "student" }), result = await studioCommand("materials", { command: "create", expectedVersion: 0, payload: { studentId: student.id, lessonId: lesson.id, title: file.name, category: "Script", storagePath: stored.storagePath, mimeType: file.type, fileSizeBytes: file.size, mediaKind: "document", role: "lesson_material" }, reason: "PDF added to lesson whiteboard" }), materialId = String(result.resource.id); setAssetUrls((urls) => ({ ...urls, [materialId]: stored.signedUrl || "" })); commit({ ...document, elements: [...document.elements, { id: crypto.randomUUID(), type: "pdf", x: 80, y: 80, width: 520, height: 560, materialId }] }); setNotice("PDF rendered on the board. Save when placement is ready."); await queryClient.invalidateQueries({ queryKey: ["studio"] }); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "PDF could not be added."); } finally { setSaving(false); } };
  const materialUrl = (id: string) => assetUrls[id] || data.materials.find((item: Material) => item.id === id)?.externalUrl || "";
  const updateText = (id: string, text: string) => { setDocument((current) => ({ ...current, elements: current.elements.map((entry) => entry.id === id && entry.type === "text" ? { ...entry, text } : entry) })); setDirty(true); };
  const updateCell = (item: Extract<WhiteboardElement, { type: "table" }>, index: number, text: string) => { const cells = [...item.cells]; cells[index] = text; setDocument((current) => ({ ...current, elements: current.elements.map((entry) => entry.id === item.id && entry.type === "table" ? { ...entry, cells } : entry) })); setDirty(true); };
  const tools = [["select", MousePointer2, "Move"], ["draw", Pencil, "Draw"], ["highlight", Highlighter, "Highlight"], ["erase", Eraser, "Erase"], ["text", TextCursorInput, "Text"], ["table", Table2, "Table"]] as const;
  const finishInsert=()=>{if(!insert)return;if(insert.type==="text"){const text=insertValue.trim();if(text)commit({...document,elements:[...document.elements,{id:crypto.randomUUID(),type:"text",x:insert.x,y:insert.y,width:280,height:90,text,color,fontSize,fontFamily,underline}]});}else{const match=insertValue.match(/^(\d+)\s*x\s*(\d+)$/i);if(!match){setNotice("Use a table size like 3x3.");return;}const rows=Math.min(10,Math.max(1,Number(match[1]))),columns=Math.min(8,Math.max(1,Number(match[2])));commit({...document,elements:[...document.elements,{id:crypto.randomUUID(),type:"table",x:insert.x,y:insert.y,width:420,height:Math.max(120,rows*44),rows,columns,cells:Array(rows*columns).fill("")}]});}setInsert(undefined);setInsertValue("");};
  return <section className="whiteboard-workspace" aria-label="Lesson whiteboard"><header><div><h2>Lesson whiteboard</h2><p>Shared visual workspace · {dirty ? "unsaved changes" : existing ? "saved" : "not created yet"}</p></div><div className="whiteboard-history"><button type="button" onClick={undo} disabled={!history.length} aria-label="Undo"><Undo2 /></button><button type="button" onClick={redo} disabled={!future.length} aria-label="Redo"><Redo2 /></button><button type="button" className="primary-button" onClick={() => void save()} disabled={saving || !dirty}><Save />{saving ? "Saving…" : "Save board"}</button><button type="button" onClick={onClose} aria-label="Close whiteboard"><X /></button></div></header>{notice && <p className="portal-notice" role="status">{notice}</p>}{insert&&<form className="whiteboard-insert-panel" onSubmit={event=>{event.preventDefault();finishInsert();}}><label>{insert.type==="text"?"Text":"Table size"}{insert.type==="text"?<textarea autoFocus value={insertValue} onChange={event=>setInsertValue(event.target.value)} placeholder="Type here…"/>:<input autoFocus value={insertValue} onChange={event=>setInsertValue(event.target.value)} pattern="\d+\s*x\s*\d+"/>}</label><div><button type="button" onClick={()=>setInsert(undefined)}>Cancel</button><button className="primary" disabled={!insertValue.trim()}>Add to board</button></div></form>}
    <div className="whiteboard-toolbar" role="toolbar" aria-label="Whiteboard tools">{tools.map(([id, Icon, label]) => <button type="button" key={id} aria-label={label} aria-pressed={tool === id} className={tool === id ? "selected" : ""} onClick={() => setTool(tool === id && id !== "select" ? "select" : id)} title={label}><Icon /><span>{label}</span></button>)}<label>Color<input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label><label>Stroke<input type="range" min="1" max="12" value={width} onChange={(event) => setWidth(Number(event.target.value))} /></label><label>Font<select value={fontFamily} onChange={(event) => setFontFamily(event.target.value)}><option>Inter</option><option>Georgia</option><option>Courier New</option></select></label><label>Size<input type="number" min="10" max="72" value={fontSize} onChange={(event) => setFontSize(Number(event.target.value))} /></label><button type="button" aria-label="Underline" className={underline ? "selected" : ""} onClick={() => setUnderline(!underline)}><u>U</u><span>Underline</span></button><label className="whiteboard-upload"><Upload /><span>Add PDF</span><input type="file" accept="application/pdf" onChange={(event) => void addPdf(event.target.files?.[0])} /></label></div>
    <div ref={board} className={`whiteboard-board tool-${tool}`} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><svg viewBox="0 0 1200 720" preserveAspectRatio="none">{document.elements.filter((item): item is Extract<WhiteboardElement, { type: "path" }> => item.type === "path").map((item) => <polyline key={item.id} points={item.points.map((value) => `${value.x},${value.y}`).join(" ")} fill="none" stroke={item.color} strokeWidth={item.width} strokeLinecap="round" strokeLinejoin="round" opacity={item.highlighted ? .45 : 1} />)}</svg>{document.elements.filter((item): item is Exclude<WhiteboardElement, { type: "path" }> => item.type !== "path").map((item) => <div key={item.id} className={`whiteboard-object ${item.type}`} style={{ left: `${item.x / 12}%`, top: `${item.y / 7.2}%`, width: `${item.width / 12}%`, height: `${item.height / 7.2}%` }} onPointerDown={(event) => objectPointer(event, item)}>{item.type === "text" && <div contentEditable suppressContentEditableWarning onPointerDown={(event) => event.stopPropagation()} onBlur={(event) => updateText(item.id, event.currentTarget.textContent || "")} style={{ color: item.color, fontSize: item.fontSize, fontFamily: item.fontFamily, textDecoration: item.underline ? "underline" : undefined }}>{item.text}</div>}{item.type === "table" && <table><tbody>{Array.from({ length: item.rows }, (_, row) => <tr key={row}>{Array.from({ length: item.columns }, (_, column) => <td key={column} contentEditable suppressContentEditableWarning onPointerDown={(event) => event.stopPropagation()} onBlur={(event) => updateCell(item, row * item.columns + column, event.currentTarget.textContent || "")}>{item.cells[row * item.columns + column]}</td>)}</tr>)}</tbody></table>}{item.type === "pdf" && (materialUrl(item.materialId) ? <object data={materialUrl(item.materialId)} type="application/pdf" aria-label="Whiteboard PDF">PDF preview unavailable. <a href={materialUrl(item.materialId)} target="_blank" rel="noreferrer">Open PDF</a></object> : <div className="pdf-placeholder">PDF is loading…</div>)}</div>)}</div>
    <footer><small>Choose Move or press Escape when you are finished with a tool. Text and table placement return to Move automatically. Mouse, pen, and touch are supported.</small></footer></section>;
}
