import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";

const args=new Set(process.argv.slice(2)); const apply=args.has("--apply"); const inputIndex=process.argv.indexOf("--input"); const inputPath=inputIndex>=0?process.argv[inputIndex+1]:"";
const record=z.record(z.string(),z.unknown()); const snapshotSchema=z.object({students:z.array(record).default([]),lessons:z.array(record).default([]),notes:z.array(record).default([]),homework:z.array(record).default([]),packages:z.array(record).default([]),payments:z.array(record).default([]),actorProfiles:z.array(record).default([]),files:z.array(record).default([]),studentAccounts:z.array(record).default([]),readerRequests:z.array(record).default([]),lessonComments:z.array(record).default([])});
const text=(value:unknown)=>String(value??"").trim(); const bool=(value:unknown,fallback=false)=>typeof value==="boolean"?value:fallback; const num=(value:unknown)=>Number(value||0);
const uuid=(namespace:string,value:unknown)=>{const hex=crypto.createHash("sha256").update(`${namespace}:${text(value)}`).digest("hex").slice(0,32).split("");hex[12]="5";hex[16]=((parseInt(hex[16],16)&3)|8).toString(16);return `${hex.slice(0,8).join("")}-${hex.slice(8,12).join("")}-${hex.slice(12,16).join("")}-${hex.slice(16,20).join("")}-${hex.slice(20).join("")}`};
function loadLegacy(){if(inputPath)return JSON.parse(fs.readFileSync(path.resolve(inputPath),"utf8"));const source=fs.readFileSync(path.resolve("assets/js/schema.js"),"utf8");return new vm.Script(`${source};({students:sampleStudents,lessons:sampleLessons,notes:sampleNotes,homework:sampleHomework,packages:samplePackages,payments:samplePayments,actorProfiles:sampleActorProfiles,files:sampleFiles,studentAccounts:typeof sampleStudentAccounts!=="undefined"?sampleStudentAccounts:[],readerRequests:typeof sampleReaderRequests!=="undefined"?sampleReaderRequests:[],lessonComments:typeof sampleLessonComments!=="undefined"?sampleLessonComments:[]})`).runInNewContext({Date,Math,JSON});}
const legacy=snapshotSchema.parse(loadLegacy()); const studioId=uuid("studio","stage-story"); const quarantine:{collection:string;id:string;reason:string;record:unknown}[]=[];
const studentIds=new Map(legacy.students.map(r=>[text(r.student_id),uuid("student",r.student_id)])); const packageIds=new Map(legacy.packages.map(r=>[text(r.package_id),uuid("package",r.package_id)])); const lessonIds=new Map(legacy.lessons.map(r=>[text(r.lesson_id),uuid("lesson",r.lesson_id)]));
const studentStatus=(value:unknown)=>({LEAD:"lead",ACTIVE:"active",PAUSED:"paused",ALUMNI:"alumni",INACTIVE:"inactive"}[text(value).toUpperCase()]||"lead");
const lessonStatus=(value:unknown)=>({DRAFT:"draft",SCHEDULED:"scheduled",COMPLETED:"completed",CANCELLED:"cancelled",LATE_CANCEL:"late_cancelled",NO_SHOW:"no_show"}[text(value).toUpperCase()]||"draft");
const students=legacy.students.flatMap(r=>{if(!text(r.full_name)){quarantine.push({collection:"students",id:text(r.student_id),reason:"Full name missing",record:r});return []}return[{id:studentIds.get(text(r.student_id)),studio_id:studioId,full_name:text(r.full_name),email:text(r.email)||null,phone:text(r.phone)||null,status:studentStatus(r.studio_status),focus_area:text(r.focus_area)||null,is_minor:bool(r.student_is_minor),portal_enabled:r.portal_access_enabled!==false,actor_page_eligible:bool(r.actor_page_eligible),version:1}]});
const lessons=legacy.lessons.flatMap(r=>{const sid=studentIds.get(text(r.student_id)),start=new Date(text(r.scheduled_start)),end=new Date(text(r.scheduled_end));if(!sid||Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start){quarantine.push({collection:"lessons",id:text(r.lesson_id),reason:"Student link or schedule invalid",record:r});return []}return[{id:lessonIds.get(text(r.lesson_id)),studio_id:studioId,student_id:sid,topic:text(r.topic||r.lesson_type)||"Lesson",starts_at:start.toISOString(),ends_at:end.toISOString(),status:lessonStatus(r.lesson_status),location_type:text(r.location_type).toUpperCase()==="IN_PERSON"?"in_person":"virtual",location_label:text(r.location_address||r.location_type)||"Studio",join_url:text(r.join_link)||null,package_id:packageIds.get(text(r.package_id))||null,version:1}]});
const packages=legacy.packages.flatMap(r=>{const sid=studentIds.get(text(r.student_id));if(!sid){quarantine.push({collection:"packages",id:text(r.package_id),reason:"Student link missing",record:r});return []}return[{id:packageIds.get(text(r.package_id)),student_id:sid,name:text(r.package_name)||"Package",price_minor:Math.round(num(r.package_price)*100),currency:"USD",expires_at:text(r.expires_at||r.expires_on)||null,credit_quantity:Math.max(1,num(r.sessions_total)||1),version:1}]});
const credits=legacy.packages.flatMap(r=>{const pid=packageIds.get(text(r.package_id));if(!pid)return[];const total=Math.max(0,num(r.sessions_total));const remaining=Math.max(0,num(r.sessions_remaining));return[{id:uuid("credit",`${r.package_id}:purchase`),package_id:pid,kind:"purchase",quantity:total||1,reason:"Migrated package purchase",idempotency_key:`migration:${r.package_id}:purchase`},...(total>remaining?[{id:uuid("credit",`${r.package_id}:consumed`),package_id:pid,kind:"adjustment",quantity:-(total-remaining),reason:"Migrated historical usage",idempotency_key:`migration:${r.package_id}:usage`}]:[])]});
const payments=legacy.payments.flatMap(r=>{const sid=studentIds.get(text(r.student_id));if(!sid)return[];return[{id:uuid("payment",r.payment_id),student_id:sid,package_id:packageIds.get(text(r.related_package_id))||null,kind:"payment",amount_minor:Math.round(num(r.amount)*100),currency:text(r.currency||"USD").toUpperCase(),external_reference:text(r.external_reference)||null,reason:text(r.review_note||r.payment_type)||"Migrated payment",created_at:text(r.payment_date||r.created_at)||new Date().toISOString()}]});
const notes=legacy.notes.flatMap(r=>{const sid=studentIds.get(text(r.student_id)),lid=lessonIds.get(text(r.lesson_id));if(!sid||!lid)return[];return[{id:uuid("note",r.note_id),student_id:sid,lesson_id:lid,title:text(r.title)||"Lesson note",body:text(r.body),status:text(r.status).toUpperCase()==="PUBLISHED"?"published":text(r.status).toUpperCase()==="ARCHIVED"?"archived":"draft",version:1}]});
const assignments=legacy.homework.flatMap(r=>{const sid=studentIds.get(text(r.student_id));if(!sid)return[];return[{id:uuid("assignment",r.homework_id),student_id:sid,lesson_id:lessonIds.get(text(r.lesson_id))||null,title:text(r.title)||"Practice",details:text(r.details),due_at:text(r.due_date)||null,status:text(r.status).toUpperCase()==="DONE"?"completed":"assigned",help_requested:bool(r.reminder_requested),version:1}]});
const materials=legacy.files.flatMap(r=>{const sid=studentIds.get(text(r.student_id));if(!sid)return[];const external=text(r.file_url||r.external_url||r.url);if(!external){quarantine.push({collection:"files",id:text(r.file_id),reason:"No storage path or URL",record:r});return[]}return[{id:uuid("material",r.file_id),studio_id:studioId,owner_student_id:sid,title:text(r.title||r.file_name)||"Material",category:text(r.category)||"Other",external_url:external,status:text(r.status).toUpperCase()==="VAULTED"?"vaulted":"active",approval_status:text(r.public_page_status).toUpperCase()==="APPROVED"?"approved":text(r.public_page_status).toUpperCase()==="PENDING_REVIEW"?"pending_review":"not_public",version:1}]});
const materialLinks=legacy.files.flatMap(r=>{const sid=studentIds.get(text(r.student_id));if(!sid||!materials.some(m=>m.id===uuid("material",r.file_id)))return[];return[{id:uuid("material-link",r.file_id),material_id:uuid("material",r.file_id),student_id:sid,lesson_id:lessonIds.get(text(r.lesson_id))||null,role:text(r.scope).toUpperCase()==="CURRENT_SCRIPT"?"current_script":text(r.scope).toUpperCase()==="LESSON_MATERIAL"?"lesson_material":text(r.material_kind).toUpperCase().includes("ACTOR")?"actor_material":"library",visible_to_student:r.student_visibility!==false}]});
const actorProfiles=legacy.actorProfiles.flatMap(r=>{const sid=studentIds.get(text(r.student_id));if(!sid)return[];return[{id:uuid("actor-profile",r.actor_profile_id||r.student_id),student_id:sid,slug:text(r.slug)||`actor-${sid.slice(0,8)}`,display_name:text(r.display_name)||students.find(s=>s.id===sid)?.full_name||"Actor",bio:text(r.bio),status:"draft",version:1}]});
const data={studios:[{id:studioId,name:"Your Studio",slug:"your-studio",timezone:"America/New_York"}],students,lessons,packages,package_credit_entries:credits,payment_entries:payments,notes,assignments,materials,material_links:materialLinks,actor_profiles:actorProfiles};
const reconciliation={source:Object.fromEntries(Object.entries(legacy).map(([k,v])=>[k,v.length])),target:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,v.length])),quarantined:quarantine.length,finance:{paymentMinor:payments.reduce((s,p)=>s+p.amount_minor,0),creditBalance:credits.reduce((s,c)=>s+c.quantity,0)},relationships:{lessonsWithStudents:lessons.filter(l=>l.student_id).length,materialsWithStudents:materials.filter(m=>m.owner_student_id).length}};
console.log(JSON.stringify({mode:apply?"apply":"dry-run",reconciliation,quarantine},null,2));
if(apply){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for --apply");if(quarantine.length)throw new Error("Migration blocked: resolve quarantined records first.");const db=createClient(url,key,{auth:{persistSession:false}});for(const [table,rows] of Object.entries(data)){if(!rows.length)continue;const {error}=await db.from(table).upsert(rows as any[],{onConflict:"id"});if(error)throw new Error(`${table}: ${error.message}`);}console.log("Migration applied and reconciled.");}
