import { Archive, CalendarDays, CheckCircle2, CircleDollarSign, FileText, FolderOpen, Mail, RefreshCw, Send, ShieldCheck, UserRound, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { formatMoney, packageSummary, studentBalanceMinor } from "../../domain/finance";
import { useStudio } from "../../hooks/useStudio";
import type { StudioSnapshot } from "../../domain/model";
import { ActionRow, EmptyState, PageHeader, Section, Status } from "../../components/Primitives";

const configs: Record<string, { title: string; description: string }> = {
  today: { title: "Today", description: "Preparation, teaching, notes, and follow-up in one continuous flow." }, students: { title: "Students", description: "People, relationships, access, current work, and the next meaningful action." }, lessons: { title: "Lessons", description: "The canonical schedule and every lesson’s explicit state." }, notes: { title: "Notes", description: "Private drafts and intentionally published student follow-up." }, materials: { title: "Materials", description: "One library with clear ownership, roles, visibility, and history." }, finance: { title: "Payments", description: "Ledger-derived balances, package credits, payments, and adjustments." }, "actor-pages": { title: "Actor Pages", description: "Draft, review, approval, and immutable published revisions." }, settings: { title: "Settings", description: "Identity, permissions, integration health, queues, and recovery." },
};
export function CoachSection() {
  const { section = "today" } = useParams();
  const config = configs[section] ?? configs.today;
  const { data } = useStudio();
  if (!data) return <div className="loading">Loading {config.title.toLowerCase()}…</div>;
  return <div className="page"><PageHeader title={config.title}>{config.description}</PageHeader>{section === "today" && <Today data={data} />}{section === "students" && <StudentsPage data={data} />}{section === "lessons" && <LessonsPage data={data} />}{section === "notes" && <NotesPage data={data} />}{section === "materials" && <MaterialsPage data={data} />}{section === "finance" && <FinancePage data={data} />}{section === "actor-pages" && <ActorPages data={data} />}{section === "settings" && <SettingsPage data={data} />}</div>;
}
type Snapshot = StudioSnapshot;
const studentName = (data: Snapshot, id: string) => data.students.find((row) => row.id === id)?.fullName ?? "Student";
function Today({ data }: { data: Snapshot }) { const ordered = [...data.lessons].filter((l) => l.status === "scheduled").sort((a,b) => a.startsAt.localeCompare(b.startsAt)); return <Section title="Teaching flow" marked><div className="workflow-list">{ordered.map((lesson, index) => <article key={lesson.id}><span>{index + 1}</span><div><strong>{studentName(data, lesson.studentId)} · {lesson.topic}</strong><small>{new Date(lesson.startsAt).toLocaleString()} · {lesson.locationLabel}</small></div><Status tone="good">{lesson.status}</Status></article>)}{!ordered.length && <EmptyState title="The day is clear" detail="New scheduled lessons will appear in chronological order." />}</div></Section>; }
function StudentsPage({ data }: { data: Snapshot }) { const navigate=useNavigate(); return <Section title="Studio roster" marked><div className="table-list">{data.students.map((student) => <article key={student.id}><span className="avatar">{student.fullName.split(" ").map(p=>p[0]).join("")}</span><div><strong>{student.fullName}</strong><small>{student.focusArea || "Focus not set"} · {student.portalEnabled ? "Portal ready" : "Access not invited"}</small></div><Status tone={student.status === "active" ? "good" : student.status === "lead" ? "warn" : "neutral"}>{student.status}</Status><button onClick={() => navigate(`/students?student=${student.id}`)}>Open</button></article>)}</div></Section>; }
function LessonsPage({ data }: { data: Snapshot }) { return <Section title="Canonical schedule" marked><div className="table-list">{[...data.lessons].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).map((lesson) => <article key={lesson.id}><CalendarDays /><div><strong>{lesson.topic} · {studentName(data, lesson.studentId)}</strong><small>{new Date(lesson.startsAt).toLocaleString()} · version {lesson.version}</small></div><Status tone={lesson.status === "completed" ? "good" : lesson.status === "scheduled" ? "neutral" : "warn"}>{lesson.status}</Status><button>Review</button></article>)}</div></Section>; }
function NotesPage({ data }: { data: Snapshot }) { const missing = data.recommendations.filter((r)=>r.reasonCode === "lesson_note_missing"); return <><Section title="Follow-up queue" marked><div>{missing.map((item)=><ActionRow key={item.id} initials="N" title={item.title} detail={item.explanation} actionLabel="Write" />)}{!missing.length && <EmptyState title="Notes are current" detail="Completed lessons without notes will appear here." />}</div></Section><Section title="Published notes"><div className="table-list">{data.notes.map(note=><article key={note.id}><FileText /><div><strong>{note.title}</strong><small>{studentName(data,note.studentId)} · version {note.version}</small></div><Status tone={note.status === "published" ? "good" : "neutral"}>{note.status}</Status></article>)}</div></Section></>; }
function MaterialsPage({ data }: { data: Snapshot }) { return <Section title="Material library" marked><div className="table-list">{data.materials.map(material=><article key={material.id}><FolderOpen /><div><strong>{material.title}</strong><small>{studentName(data,material.studentId)} · {material.role.replaceAll("_"," ")} · {material.category}</small></div><Status tone={material.approvalStatus === "approved" ? "good" : "neutral"}>{material.status}</Status><button>Open</button></article>)}</div></Section>; }
function FinancePage({ data }: { data: Snapshot }) { return <><Section title="Package ledger" marked><div className="table-list">{data.packages.map(pkg=>{const summary=packageSummary(pkg,data.creditEntries);return <article key={pkg.id}><CircleDollarSign /><div><strong>{studentName(data,pkg.studentId)} · {pkg.name}</strong><small>{summary.remainingCredits} credits remaining · {formatMoney(pkg.priceMinor,pkg.currency)}</small></div><Status tone={summary.remainingCredits<=1?"warn":"good"}>{summary.remainingCredits} left</Status><button>Review</button></article>})}</div></Section><Section title="Payment ledger"><div className="table-list">{data.students.map(student=><article key={student.id}><CheckCircle2 /><div><strong>{student.fullName}</strong><small>Immutable payment, refund, and adjustment entries</small></div><strong>{formatMoney(studentBalanceMinor(student.id,data.payments))}</strong></article>)}</div></Section></>; }
function ActorPages({ data }: { data: Snapshot }) { return <Section title="Publishing workflow" marked><div className="table-list">{data.actorProfiles.map(profile=><article key={profile.id}><UserRound /><div><strong>{profile.displayName}</strong><small>/actors/{profile.slug} · version {profile.version}</small></div><Status tone={profile.status === "published" ? "good" : "warn"}>{profile.status.replaceAll("_"," ")}</Status><button>Review</button></article>)}{!data.actorProfiles.length&&<EmptyState title="No actor pages yet" detail="Eligible student drafts will appear here."/>}</div></Section>; }
function SettingsPage({ data }: { data: Snapshot }) { return <><Section title="Integration health" marked><div className="settings-grid"><article><CheckCircle2/><strong>Supabase</strong><small>Canonical database, Auth, RLS, and Storage</small><Status tone="good">ready</Status></article><article><RefreshCw/><strong>Google Calendar</strong><small>Projection queue · conflicts require review</small><Status tone="good">ready</Status></article><article><Mail/><strong>Gmail</strong><small>Approved messages enter the outbox</small><Status tone="warn">configuration required</Status></article><article><ShieldCheck/><strong>Security</strong><small>Role and relationship policies enforced by RLS</small><Status tone="good">enforced</Status></article></div></Section><Section title="Communication outbox"><div className="table-list">{data.outbox.map(message=><article key={message.id}><Send/><div><strong>{message.subject}</strong><small>{message.recipient} · {message.attempts} attempts</small></div><Status>{message.status}</Status></article>)}{!data.outbox.length&&<EmptyState title="Outbox is clear" detail="Approved messages will queue here with delivery history."/>}</div></Section></>; }
